version: '3.8'

services:
  app:
    image: 'faceit-pocket-stats'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - app-node_modules:/app/node_modules
      - app-next:/app/.next

volumes:
  app-node_modules:
  app-next: